Feature/issue 8 categories
PlatziMaster/fake-store-api pull request #10
Opened 2021-08-29 21:39 UTC by eriksape

**What type of PR is this?**
* Feature

**What this PR does / why we need it:**
This PR adds POST for categories

**Which issue(s) this PR fixes:**
#8 

**Special notes for your reviewer:**
Added e2e test, the root (`POST /`) test changed from 200 to 404

**Does this PR introduce a user-facing change?:**
Added endpoint `/api/categories POST`

**Additional documentation**
See the changelog

2021-08-31 01:23 UTC, nicobytes requested changes

2021-08-31 01:23 UTC, nicobytes commented on src/controllers/categories/categories.controller.ts
> +  async create(@Body() category: CreateCategorytDto) {
@eriksape Aquí podríamos ahorrarnos el `async` y `await`, ya que no se usan, además en método `create` ya es una promise entonces NestJs lo resuelve.

2021-09-07 17:26 UTC, eriksape commented on src/controllers/categories/categories.controller.ts
> +  async create(@Body() category: CreateCategorytDto) {
removed the async in the update

2021-09-07 22:32 UTC, nicobytes requested changes

2021-09-07 22:32 UTC, nicobytes commented on libs/data-set/src/data-set.service.ts
> +    for (const data of dataSet) {
@eriksape creo funciona igual si nos evitamos el for y usamos:
`this.dataSet = [...this.dataSet, ...dataSet]`

2021-09-07 22:32 UTC, nicobytes commented on libs/data-set/src/data-set.service.ts
> +    const createdDataSet = { id: this.id, ...newDataSet };
@eriksape el naming aqui no es adecuado `createdDataSet` parece que fuera un nuevo dataSet pero al final es solo un item que se agrega al dataSet actual, puede ser algo como `newItem`.

2021-09-07 22:32 UTC, nicobytes commented on libs/data-set/src/data-set.service.ts
> +  filter(key: string, value: string | number): DataSetService<T> {
@eriksape es un muy buen método, pero `filter` debería funciona como propósito general y también para varios valores como:

```ts
dataSet.filter({ 'age': 36, 'active': true });
```

te propongo que repliquemos el método [filter ](https://github.com/sindresorhus/filter-obj/blob/main/index.js) de [lodash](https://lodash.com/docs/4.17.15#filter)

o mejor que agreguemos lodash como dependencia y hagamos el filtro por ahí para no recrear la rueda, eso si usando lodash/fp para no traer el peso de toda la lib sino solo de las funciones que vayamos necesitando.

Tambien podemos obviar el método `get` ya que en otras APIs (TypeOrm o Mongoose) cuando envias un filter sin nada por defecto retorna el array completo.

```ts
dataSet.filter();
```

Y para hacer la busqueda por id creo debería existir el método `getById` y yap ya que todos tienen un id.

Finalmente creo el método debería llamarse `find`.

```ts
dataSet.find({ 'age': 36, 'active': true });
dataSet.find({ 'title': 'my-title'});
dataSet.find();
```

Sin embargo hay un problema y es en filtros más complejos como rangos por ejemplo:

```ts
dataSet.find({price: { max: 100, min: 0 }});
```

En ese caso vi estas referencias:

https://gist.github.com/jherax/f11d669ba286f21b7a2dcff69621eb72
https://gist.github.com/diegochavez/e9019fedefa0553ce7efc12857739322

2021-09-08 12:35 UTC, eriksape commented on libs/data-set/src/data-set.service.ts
> +    for (const data of dataSet) {
Actualizado en el PR 😄 se m hace mas legible eso si.

2021-09-08 12:36 UTC, eriksape commented on libs/data-set/src/data-set.service.ts
> +    const createdDataSet = { id: this.id, ...newDataSet };
Si esa convención de nombre tampoco me pareció adecuada 😩 se me hace mas simple el newItem

2021-09-08 12:39 UTC, eriksape commented on libs/data-set/src/data-set.service.ts
> +  filter(key: string, value: string | number): DataSetService<T> {
🤔 por lo pronto lo acoté al **object de primer nivel, string, string[], y al Function**. No se si pudiéramos dejarlo para otro PR el object multinivel como una mejora de la libreria DataSet, el category en este caso es solamente un nivel, el product le pudiera servir más el multinivel. Creo que para este PR esta un poco fuera de scope aunque si me gusta la idea.

2021-09-16 22:19 UTC, nicobytes submitted a review, later dismissed

2021-09-24 21:26 UTC, nicobytes submitted a review, later dismissed

2021-10-04 22:27 UTC, merged