Implement CI for Linter
PlatziMaster/fake-store-api pull request #11
Opened 2021-09-03 03:10 UTC by MigueMartelo

## DESCRIPTION
Implement CI for Lint.
 - Add husky to run the ESLint with each commit.
 - Add actions for run ESLint with each pull request. 
 
## Which issue(s) this PR fixes:
#3

2021-09-07 21:58 UTC, nicobytes requested changes

2021-09-07 21:58 UTC, nicobytes commented on package.json
> +    "husky": "^7.0.2",
@MigueMartelo No es buena practica usar el símbolo ^ en prod ya que eso puede hacer que se descarguen versiones actuales de una lib para que el sistema no esta listo, incluso si se tiene el package lock es buena practica tener la versión exacta.

Si puedes de una vez hacer pin a las demás dependencias estaría genial!

Algunas referencias:
https://docs.renovatebot.com/dependency-pinning/
https://the-guild.dev/blog/how-should-you-pin-dependencies-and-why

2021-09-07 21:58 UTC, nicobytes commented on .github/workflow/ci.yml
> +      run: npm install
@MigueMartelo deberiamos usar `npm ci` que sería igual que `npm install` pero el ci es instalarlas para procesod de CI (Continuos Integration) , tiene ventajas como:

- Es más rapido
- Instala las versiones exactas.
- Se asegura de eliminar node_modules para iniciar desde cero, etc

Ref: https://docs.npmjs.com/cli/v7/commands/npm-ci

2021-09-08 02:44 UTC, MigueMartelo commented on package.json
> +    "husky": "^7.0.2",
Done @nicobytes

2021-09-08 02:45 UTC, MigueMartelo commented on .github/workflow/ci.yml
> +      run: npm install
Done! @nicobytes

2021-09-14 01:14 UTC, nicobytes approved these changes

2021-09-14 01:14 UTC, merged