Filter by price
PlatziMaster/fake-store-api pull request #2
Opened 2021-08-26 03:04 UTC by juanjosevega99

fIX #1

2021-09-07 21:52 UTC, nicobytes requested changes

2021-09-07 21:52 UTC, nicobytes commented on src/services/products/products.service.spec.ts
> +      let productsAll = service.getAll(filters);
@juanjosevega99 debería ser `const` ya que no cambia en todo el proceso.

2021-09-07 21:52 UTC, nicobytes commented on src/services/products/products.service.spec.ts
> +      let productsAll = service.getAll(filters);
@juanjosevega99 debería ser `const` ya que no cambia en todo el proceso.

2021-09-07 21:52 UTC, nicobytes commented on src/services/products/products.service.spec.ts
> +      let productsAll = service.getAll(filters);
@juanjosevega99 debería ser `const` ya que no cambia en todo el proceso.

2021-09-08 01:04 UTC, juanjosevega99 commented on src/services/products/products.service.spec.ts
> +      let productsAll = service.getAll(filters);
Fixed!

2021-09-16 22:16 UTC, nicobytes approved these changes

2021-09-16 22:16 UTC, merged